apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-deployment
spec:
  selector:
     matchLabels:
       app: dagster
  replicas: 1
  template:
    metadata:
     labels:
        app: dagster
    spec:
      containers:
      - name: dagster
        image: dagster/dagster-k8s:latest
        ports:
        - containerPort: 80
          name: dagster-svc
        env:
         - name: FTLCONF_LOCAL_IPV4
           value: 192.168.1.39
#        volumeMounts:
#          - mountPath: /
#            name: dagster-storage
      volumes:
         - name: dagster-data
           persistentVolumeClaim:
             claimName: dagster-pvc