apiVersion: v1
kind: PersistentVolume
metadata:
  name: ph
  labels:
    type: "local"
spec:
  storageClassName: local-storage
  capacity:
    storage: "500Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/ssd/pihole"