apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  airflow.cfg: |
    [database]
    sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
    [core]
    executor = KubernetesExecutor
    load_examples = False
    [scheduler]
    min_file_process_interval = 60
    scheduler_max_threads = 1
    [kubernetes_executor]
    namespace = airflow
    delete_worker_pods = True
    worker_container_repository = apache/airflow
    worker_container_tag = 2.9.3
    worker_container_cpu_limit = 200m
    worker_container_memory_limit = 256Mi
    [webserver]
    web_server_master_timeout = 300
