apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
  labels:
    app: airflow
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow
        component: scheduler
    spec:
      containers:
      - name: scheduler
        image: apache/airflow:2.9.3
        command: ["airflow", "scheduler"]
        volumeMounts:
        - name: config
          mountPath: /opt/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: logs
          mountPath: /airflow/logs
        resources:
          limits:
            cpu: "400m"
            memory: "700Mi" # Increased for db init
          requests:
            cpu: "100m"
            memory: "384Mi" # Increased
      volumes:
      - name: config
        configMap:
          name: airflow-config
      - name: logs
        persistentVolumeClaim:
          claimName: airflow-logs
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - k3swrk3 # Replace with Pi 3B hostname
      tolerations:
      - key: "low-memory"
        operator: "Exists"
        effect: "NoSchedule"
