apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: airflow
type: Opaque
stringData:
  webserver-secret-key: "this-is-a-secret-key-change-me" # Change this
  admin-username: admin
  admin-password: admin # Change post-deployment
