apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  labels:
    app: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  template:
    metadata:
      labels:
        app: unifi
    spec:
      nodeSelector:
          kubernetes.io/hostname: k3swrk1
      containers:
        - name: unifi
          image: jacobalberty/unifi:v9.1
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
            - containerPort: 3478
              name: stun
              protocol: UDP
            - containerPort: 10001
              name: discovery
              protocol: UDP
            - containerPort: 6789
              name: speedtest
            - containerPort: 1900
              name: ssdp
              protocol: UDP
          env:
            - name: UNIFI_HTTP_PORT
              value: "8080"
            - name: UNIFI_HTTPS_PORT
              value: "8443"
            - name: UNIFI_STUN_PORT
              value: "3478"
          volumeMounts:
            - name: unifi-data
              mountPath: /unifi
      volumes:
        - name: unifi-data
          persistentVolumeClaim:
            claimName: unifi-data-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/var/lib/rancher/k3s/storage/pvc-c0e9c541-2412-4151-a8d8-26d050228173_default_unifi-data"  # use actual path
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3swrk1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: unifi-data-pv
  storageClassName: manual
---
apiVersion: v1
kind: Service
metadata:
  name: unifi
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.6
  selector:
    app: unifi
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
    - name: stun
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: discovery
      port: 10001
      targetPort: 10001
      protocol: UDP
    - name: speedtest
      port: 6789
      targetPort: 6789
    - name: ssdp
      port: 1900
      targetPort: 1900
      protocol: UDP
